"""initial schema

Revision ID: a785c819fa5f
Revises: 
Create Date: 2026-06-27 11:09:50.658732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from api.db.fts import FTS_DDL


# revision identifiers, used by Alembic.
revision: str = 'a785c819fa5f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('exercises',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('canonical_name', sa.String(), nullable=False),
    sa.Column('primary_muscles', sa.JSON(), nullable=False),
    sa.Column('secondary_muscles', sa.JSON(), nullable=False),
    sa.Column('equipment', sa.String(), nullable=True),
    sa.Column('mechanic', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('provenance', sa.String(), nullable=False),
    sa.Column('canonical_exercise_id', sa.Integer(), nullable=True),
    sa.Column('created_by_user_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['canonical_exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exercises_canonical_exercise_id'), ['canonical_exercise_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_exercises_canonical_name'), ['canonical_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_exercises_provenance'), ['provenance'], unique=False)
        batch_op.create_index(batch_op.f('ix_exercises_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('programs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('programs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_programs_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_programs_user_id'), ['user_id'], unique=False)

    op.create_table('workout_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workout_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workout_templates_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workout_templates_user_id'), ['user_id'], unique=False)

    op.create_table('exercise_aliases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('alias_text', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exercise_aliases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exercise_aliases_exercise_id'), ['exercise_id'], unique=False)

    op.create_table('program_weeks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('week_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('program_weeks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_program_weeks_program_id'), ['program_id'], unique=False)

    op.create_table('template_exercises',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('target_sets', sa.Integer(), nullable=True),
    sa.Column('target_reps', sa.Integer(), nullable=True),
    sa.Column('rest_seconds', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['workout_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('template_exercises', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_template_exercises_exercise_id'), ['exercise_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_template_exercises_template_id'), ['template_id'], unique=False)

    op.create_table('program_slots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('program_week_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('day_index', sa.Integer(), nullable=False),
    sa.Column('progression_rule', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['program_week_id'], ['program_weeks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['workout_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('program_slots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_program_slots_program_week_id'), ['program_week_id'], unique=False)

    op.create_table('workout_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('program_slot_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['program_slot_id'], ['program_slots.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['workout_templates.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workout_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workout_sessions_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workout_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('session_exercises',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('target_sets', sa.Integer(), nullable=True),
    sa.Column('target_reps', sa.Integer(), nullable=True),
    sa.Column('rest_seconds', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['workout_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('session_exercises', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_session_exercises_exercise_id'), ['exercise_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_session_exercises_session_id'), ['session_id'], unique=False)

    op.create_table('set_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_exercise_id', sa.Integer(), nullable=False),
    sa.Column('set_number', sa.Integer(), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('rpe', sa.Float(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('is_warmup', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_exercise_id'], ['session_exercises.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('set_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_set_entries_session_exercise_id'), ['session_exercise_id'], unique=False)

    # ### end Alembic commands ###
    op.execute(FTS_DDL)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('set_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_set_entries_session_exercise_id'))

    op.drop_table('set_entries')
    with op.batch_alter_table('session_exercises', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_session_exercises_session_id'))
        batch_op.drop_index(batch_op.f('ix_session_exercises_exercise_id'))

    op.drop_table('session_exercises')
    with op.batch_alter_table('workout_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workout_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_workout_sessions_tenant_id'))

    op.drop_table('workout_sessions')
    with op.batch_alter_table('program_slots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_program_slots_program_week_id'))

    op.drop_table('program_slots')
    with op.batch_alter_table('template_exercises', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_template_exercises_template_id'))
        batch_op.drop_index(batch_op.f('ix_template_exercises_exercise_id'))

    op.drop_table('template_exercises')
    with op.batch_alter_table('program_weeks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_program_weeks_program_id'))

    op.drop_table('program_weeks')
    with op.batch_alter_table('exercise_aliases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exercise_aliases_exercise_id'))

    op.drop_table('exercise_aliases')
    with op.batch_alter_table('workout_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workout_templates_user_id'))
        batch_op.drop_index(batch_op.f('ix_workout_templates_tenant_id'))

    op.drop_table('workout_templates')
    with op.batch_alter_table('programs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_programs_user_id'))
        batch_op.drop_index(batch_op.f('ix_programs_tenant_id'))

    op.drop_table('programs')
    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exercises_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_exercises_provenance'))
        batch_op.drop_index(batch_op.f('ix_exercises_canonical_name'))
        batch_op.drop_index(batch_op.f('ix_exercises_canonical_exercise_id'))

    op.drop_table('exercises')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_tenant_id'))

    op.drop_table('users')
    op.drop_table('tenants')
    # ### end Alembic commands ###
    op.execute("DROP TABLE IF EXISTS exercises_fts")
