"""Link a Program to the Objective it trains for (programs.objective_id).

Revision ID: a7b8c9d0e1f2
Revises: f5a6b7c8d9e0
Create Date: 2026-06-28

The coach's strategy (``spec.coach_summary``) is plan-scoped, but a plan had no
link to the objective it was built for. Add a nullable ``objective_id`` FK
(SET NULL on objective delete) so the active plan's strategy can be surfaced
alongside the objective.

NOTE: exercises_fts* are SQLite FTS5 shadow tables (api/db/fts.py, not the ORM);
any autogenerated DROP of them is intentionally omitted.
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "a7b8c9d0e1f2"
down_revision: Union[str, Sequence[str], None] = "f5a6b7c8d9e0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # SQLite can't ALTER ADD a column with an inline FK; add the column in batch
    # mode so a table rebuild carries the FK + ON DELETE SET NULL.
    with op.batch_alter_table("programs", schema=None) as batch_op:
        batch_op.add_column(sa.Column("objective_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            "fk_programs_objective_id",
            "objectives",
            ["objective_id"],
            ["id"],
            ondelete="SET NULL",
        )
    op.create_index("ix_programs_objective_id", "programs", ["objective_id"])


def downgrade() -> None:
    op.drop_index("ix_programs_objective_id", table_name="programs")
    with op.batch_alter_table("programs", schema=None) as batch_op:
        batch_op.drop_constraint("fk_programs_objective_id", type_="foreignkey")
        batch_op.drop_column("objective_id")
